### ISSUE TITLE
SVG icon not rendering on IE Edge under Lightning UI.

### ISSUE THREAD

**Issue by kanwalpreet-singh** [salesforce-ux/design-system#247]
Create Visualforce page and Tab. The svg icons are not rendered on IE edge browser. The visualforce code of page is - 

``` xml
<apex:page sidebar="false" showHeader="false" docType="html-5.0" applyHtmlTag="false">
  <html xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <head>
            <meta charset="UTF-8"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />

            <apex:stylesheet value="path to slds css" />

            <apex:includeScript value="path to svg4everybody" />

        </head>
        <body style="padding: 0;">
            <div class="slds">
                <span class="slds-icon_container slds-icon_container--circle slds-icon-action-description" title="description of icon when needed">
                  <svg aria-hidden="true" class="slds-icon slds-icon--small">
                    <use xlink:href="path to slds#description"></use>
                  </svg>
                  <span class="slds-assistive-text">Description of icon</span>
                </span>
            </div>
            <script>
                svg4everybody();
            </script>   
        </body>
  </html>       
</apex:page>
```

**Comment by kaelig** [comment]
Thank you for using the Lightning Design System and reporting this, @kanwalpreet-singh!

Have you tried using the Lightning icon helper as documented in this tutorial? https://www.lightningdesignsystem.com/resources/lightning-svg-icon-component-helper/

**Comment by kanwalpreet-singh** [comment]
Sorry for the late reply, but this solution is not working at all. I am not able to use it on visualforce page.

**Comment by kaelig** [comment]
Thank you for trying, @kanwalpreet-singh. Can you confirm you tried including the SVG4Everybody polyfill?

**Comment by kanwalpreet-singh** [comment]
Yes, i am already using SVG4Everybody. It works fine on all other browsers including other versions of IE. The issue occurs when page is opened under lightning experience on IE edge.

**Comment by stefsullrew** [comment]
This is something we're currently looking at. It's related to the way SVGs currently must be injected with JS. Stay tuned.

**Comment by kanwalpreet-singh** [comment]
The thing is inside lightning experience if i use aura component to render svg it works bu when i try to use on visualforce page doing it standard way it is not working.

**Comment by kylethornton** [comment]
@stefsullrew has there been any progress made on this?

**Comment by ButuzGOL** [comment]
any progress ?

**Comment by ButuzGOL** [comment]
Temporary fix is to set absolute path for svg
like this 
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="https://na30.lightning.force.com/resource/1475746227000/demo__slds/assets/icons/custom-sprite/svg/symbols.svg#custom67"></use>

**Comment by kaelig** [comment]
@stefsullrew has followed up with developers and should have more information by now. Stef?

**Comment by kaelig** [comment]
This should be fixed very soon in Spring ’17. Feel free to reopen if you keep running into it!

**Comment by MattSynaptic** [comment]
I'm still seeing this issue on a visualforce page in Edge in Lightning Experience and we now in Summer 17.

**Comment by vc4u** [comment]
Yes, the issue still seems to persist for IE Edge + Visualforce + SVG  (with svg4everybody loaded and called).

**Comment by MattSynaptic** [comment]
Updating to the new version of svg4Everybody worked. Thanks!

**Comment by gunda223** [comment]
I still have the same issue in IE 11, Is this fixed?

**Comment by MattSynaptic** [comment]
Yes, on vc4u's recommendation I updated svg4everybody to the recent v2.1.9 release and that fixed it for me.
