### ISSUE TITLE
Compiling index-ltng.scss results in CSS that does not load salesforce fonts

### ISSUE THREAD

**Issue by sdruckerfig** [salesforce-ux/design-system#71]
Trying to create a custom stylesheet.

Have created the following config.rb in the root project folder:

http_path = "/"
css_dir = "assets/styles"
sass_dir = "scss"
images_dir = "assets/images"
javascripts_dir = "javascripts"
output_style = :expanded

Then issue the following command:

compass compile scss/index-ltng.scss

Then I upload the assets folder as a static resource and insert a reference from my app.

Everything seems to work, except that the browser doesn't load the Salesforce-Sans fonts. I'm not getting a 404 -- it just seems like the @font-face might be missing somehow.

On a side note, it would be great if there was official instructions as to how to compile the stylesheet with sass/compass.

**Comment by srohde** [comment]
Thanks for the feedback. We are looking into it.

**Comment by kaelig** [comment]
Note: this could be related to #83 and #99.

**Comment by 3den** [comment]
@sdruckerfig @kaelig I got the fonts to work on a rails app with the following code:

```scss
// This is needed to fix loadind fonts
// https://github.com/salesforce-ux/design-system/issues/71
@mixin set-slds-font($name, $file, $weight: 400, $style: normal) {
  @font-face {
      font-family: "Salesforce Sans";
      font-weight: $weight;
      font-style: $style;
      src: font-files(
        "salesforce-lightning-design-system/assets/fonts/webfonts/" + $file + ".woff",
        "salesforce-lightning-design-system/assets/fonts/webfonts/" + $file + ".woff2",
        "salesforce-lightning-design-system/assets/fonts/webfonts/" + $file + ".eot",
        "salesforce-lightning-design-system/assets/fonts/webfonts/" + $file + ".svg"
      );
  }
}

@include set-slds-font("Salesforce Sans", "SalesforceSans-Light", 300);
@include set-slds-font("Salesforce Sans", "SalesforceSans-LightItalic", 300, italic);
@include set-slds-font("Salesforce Sans", "SalesforceSans-Regular", 400);
@include set-slds-font("Salesforce Sans", "SalesforceSans-Italic", 400, italic);
@include set-slds-font("Salesforce Sans", "SalesforceSans-Bold", 700);
@include set-slds-font("Salesforce Sans", "SalesforceSans-BoldItalic", 700, italic);
```

If you use relative paths on the `font-files` it should work the same.

**Comment by kaelig** [comment]
This was fixed in the new v1.0.2. Thank you for your patience!

**Comment by 3den** [comment]
this bug is not fixed https://github.com/salesforce-ux/design-system/issues/211

**Comment by kaelig** [comment]
The `$slds-load-webfonts` setting is now available, allowing developers to load fonts with an alternative method of their choice. I hope this helps and thank you all for reporting this!
